language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq mono-devel mono-gmcs
  - mozroots --import --sync
  - export EnableNuGetPackageRestore=true

install:
  - nuget restore GitterClient.sln
  
script:
  - xbuild /p:Configuration=Release GitterClient.sln

notifications:
  email:
    - wassim.azirar@gmail.com

env:
  global:
    - EnableNuGetPackageRestore=true
