language: csharp
solution: GitterClient.sln
sudo: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gtk-sharp2
  - mozroots --import --sync
  - export EnableNuGetPackageRestore=true
script:
  - xbuild /p:Configuration=Release GitterClient.sln
env:
  global:
    - EnableNuGetPackageRestore=true
