language: csharp
solution: GitterClient.sln
env:
  global:
    - EnableNuGetPackageRestore=true
sudo: true
before_install:
  # Make sure mono is installed,
  # pipe stdout to dev/null because qq is still too chatty
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -y gtk-sharp2  > /dev/null
  - sudo apt-get install -qq mono-devel > /dev/null
  - mozroots --import --sync
  - export EnableNuGetPackageRestore=true
script:
  - xbuild /p:Configuration=Release GitterClient.sln
